-- Structured buy-box fields for developers (luxury) and flippers (distressed).
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "company" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "preferredContact" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "decisionMaker" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "buyingFrequency" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "priceRange" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "closingSpeed" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "dealType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "buildType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "minLotSize" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "marketDetails" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "minBeds" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "maxBaths" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "propertyType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "conditionTolerance" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MarketContact" ADD COLUMN IF NOT EXISTS "needsView" TEXT NOT NULL DEFAULT '';
