import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

// Duration goals stored in SECONDS. 1:00 = 3600, 2:00 = 7200.
const H = 3600;

// --- KPI catalog v2: organized by role -------------------------------------
// category drives alert severity (green=hard, blue=soft, yellow/red=silent).
// roleKey ties a per_rep KPI to a position; "" = team-wide.
const KPIS = [
  // ===== Cold Call / Lead Manager (Irish) =====
  // Cold-call dials are DORMANT during the PPL transition (tracked, no alerts).
  // Irish's live goal is Appointments Set (per-rep target = 5/day, see TARGETS).
  { key: "appts_set", name: "Appointments Set", emoji: "📅", category: "green", unit: "count", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: 3, goalKind: "at_least", definition: "Appointments booked from the leads we send (PPL/SMS/mail). Stretch over Irish's ~2.3 proven best." },
  { key: "passoffs", name: "Passoffs to Acquisitions", emoji: "🔁", category: "green", unit: "count", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Live transfers / appts handed to an Acquisition rep." },
  { key: "leads_generated", name: "Leads Generated (Caller)", emoji: "✅", category: "green", unit: "count", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Leads generated by the caller's own outreach. Feeds monthly Cost/Lead." },
  { key: "outbound_calls", name: "Outbound Dials", emoji: "📞", category: "blue", unit: "count", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: 120, goalKind: "at_least", definition: "Dials made. ~24/hr over a 5h day." },
  { key: "connected_calls", name: "Connections", emoji: "☎️", category: "blue", unit: "count", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: 90, goalKind: "at_least", definition: "Calls where a prospect was reached; tracks the 120 dials." },
  { key: "quality_convos", name: "Quality Conversations", emoji: "💬", category: "blue", unit: "count", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: 10, goalKind: "at_least", definition: "Conversation showing interest in selling. Just above Irish's 8.7 proven." },
  { key: "leads_cc", name: "Leads (Cold Call)", emoji: "🧊", category: "yellow", unit: "count", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Leads from cold calling (dormant)." },
  { key: "cc_talk_time", name: "Talk Time", emoji: "🎙️", category: "blue", unit: "duration", scope: "per_rep", roleKey: "cc_lm", cadence: "daily", goalValue: 1 * H, goalKind: "at_least", definition: "Time on the phone." },

  // ===== Acquisitions (Michelle, Ethan, Jon) =====
  { key: "leads_worked", name: "Follow Ups", emoji: "📲", category: "blue", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Lead follow-ups completed." },
  { key: "appts_taken", name: "Appointments Attended", emoji: "🤝", category: "green", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Seller appointments actually attended (count)." },
  { key: "completed_process_calls", name: "Completed Process Calls", emoji: "🗂️", category: "blue", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Process calls completed with sellers." },
  { key: "offers_made", name: "Verbal Offers Made", emoji: "💬", category: "green", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: 2, goalKind: "at_least", definition: "Verbal offers made to sellers." },
  { key: "offers_rejected", name: "Offers Rejected", emoji: "❌", category: "yellow", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Offers the seller rejected (visibility — diagnose pricing/approach)." },
  { key: "acq_contracts_sent", name: "Contracts Sent", emoji: "📤", category: "green", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Contracts this rep sent today." },
  { key: "acq_signed_assignment", name: "Signed — Assignment", emoji: "🖊️", category: "green", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Contracts signed as an Assignment." },
  { key: "acq_signed_novation", name: "Signed — Novation", emoji: "🖊️", category: "green", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Contracts signed as a Novation." },
  { key: "acq_signed_listing", name: "Signed — Listing", emoji: "🖊️", category: "green", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Contracts signed as a Listing." },
  { key: "acq_signed_creative", name: "Signed — Creative", emoji: "🖊️", category: "green", unit: "count", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Contracts signed as a Creative deal." },
  { key: "acq_talk_time", name: "Total Talk Time", emoji: "🎧", category: "blue", unit: "duration", scope: "per_rep", roleKey: "acquisitions", cadence: "daily", goalValue: 90 * 60, goalKind: "at_least", definition: "Total time on the phone with sellers." },

  // ===== Dispositions (Sharyn, Marie) =====
  { key: "buyers_contacted", name: "Buyers Contacted", emoji: "📇", category: "blue", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: 80, goalKind: "at_least", definition: "Buyers reached out to. Base = Marie (25h); Sharyn target 140." },
  { key: "new_buyers", name: "New Buyers Added", emoji: "➕", category: "green", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: 2, goalKind: "at_least", definition: "New qualified cash buyers added. ~ proven buyers-qualified." },
  { key: "deals_under_contract", name: "Deals Under Contract", emoji: "📑", category: "yellow", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Active deals currently being marketed." },
  { key: "deals_sold", name: "Deals Sent to Buyers", emoji: "📤", category: "green", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: 2, goalKind: "at_least", definition: "Number of buyers we sent the deal to for review (interested buyers). Base = Marie; Sharyn target 4." },
  { key: "buyer_offers_received", name: "Buyer Offers Received", emoji: "📥", category: "green", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Offers received back from buyers on our deals." },
  { key: "contracts_assigned", name: "Contracts Assigned", emoji: "🏁", category: "green", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Deals we got assigned/sold to a buyer (closed assignment)." },
  { key: "deals_comped", name: "Deals Comped", emoji: "💰", category: "blue", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Deals we ran comps on." },
  { key: "avg_days_to_sell", name: "Avg Days-to-Sell", emoji: "⏳", category: "yellow", unit: "count", scope: "per_rep", roleKey: "dispositions", cadence: "daily", goalValue: null, goalKind: "at_most", definition: "Average days a deal sits before sold (lower is better)." },

  // ===== Lead sources — daily (PPL model, team-shared) =====
  { key: "ppl_leads", name: "PPL Leads (Purchased/Inbound)", emoji: "🎟️", category: "green", unit: "count", scope: "team", roleKey: "", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Paid-per-lead leads purchased + inbound leads received." },
  { key: "text_responses", name: "Text Responses", emoji: "💬", category: "blue", unit: "count", scope: "team", roleKey: "", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Positive responses from SMS campaigns." },
  { key: "direct_mail_responses", name: "Direct Mail Responses", emoji: "📮", category: "blue", unit: "count", scope: "team", roleKey: "", cadence: "daily", goalValue: null, goalKind: "tracked", definition: "Responses from direct mail." },

  // ===== Team — monthly money (entered) =====
  { key: "contracts_sent", name: "Contracts Sent", emoji: "📤", category: "green", unit: "count", scope: "team", roleKey: "", cadence: "monthly", goalValue: 20, goalKind: "at_least", definition: "Contracts sent this month. ~0.9/active-day per closer." },
  { key: "contracts_signed", name: "Contracts Signed", emoji: "🖊️", category: "green", unit: "count", scope: "team", roleKey: "", cadence: "monthly", goalValue: 6, goalKind: "at_least", definition: "Contracts signed this month. Grounded in ~0.16 signed/active-day." },
  { key: "deals_closed", name: "Deals Closed", emoji: "🏆", category: "green", unit: "count", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", definition: "Deals closed this month." },
  { key: "gross_revenue", name: "Gross Revenue", emoji: "💰", category: "green", unit: "currency", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", definition: "Gross revenue for the month." },
  { key: "marketing_spend", name: "Marketing Spend", emoji: "📣", category: "green", unit: "currency", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", definition: "Marketing spend for the month." },
  { key: "operating_expenses", name: "Operating Expenses", emoji: "🧾", category: "green", unit: "currency", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", definition: "Operating expenses for the month." },

  // ===== Team — monthly computed ratios (never entered) =====
  { key: "revenue_per_lead", name: "Revenue per Lead", emoji: "📈", category: "yellow", unit: "currency", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", computed: true, formula: "revenue_per_lead", definition: "Gross Revenue ÷ Total Leads." },
  { key: "revenue_per_deal", name: "Revenue per Deal", emoji: "📈", category: "yellow", unit: "currency", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", computed: true, formula: "revenue_per_deal", definition: "Gross Revenue ÷ Deals Closed." },
  { key: "cost_per_lead", name: "Cost per Lead", emoji: "📉", category: "yellow", unit: "currency", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", computed: true, formula: "cost_per_lead", definition: "Marketing Spend ÷ Total Leads." },
  { key: "cost_per_deal", name: "Cost per Deal", emoji: "📉", category: "yellow", unit: "currency", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", computed: true, formula: "cost_per_deal", definition: "Marketing Spend ÷ Deals Closed." },
  { key: "net_margin", name: "Net Margin", emoji: "％", category: "yellow", unit: "percent", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", computed: true, formula: "net_margin", definition: "(Revenue − Mktg − OpEx) ÷ Revenue." },
  { key: "marketing_roi", name: "Marketing ROI", emoji: "🧮", category: "yellow", unit: "ratio", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", computed: true, formula: "marketing_roi", definition: "(Revenue − Mktg) ÷ Mktg." },
  { key: "company_roi", name: "Company ROI", emoji: "🧮", category: "yellow", unit: "ratio", scope: "team", roleKey: "", cadence: "monthly", goalValue: null, goalKind: "tracked", computed: true, formula: "company_roi", definition: "(Revenue − Mktg − OpEx) ÷ (Mktg + OpEx)." },
];

// Reps with their positions. Emails are placeholders — edit in Admin.
const USERS = [
  { name: "Michelle", email: "michelle@example.com", role: "rep", position: "acquisitions", note: "Lead Mgr + Dispositions Mgr + Acquisition closer. Goals halved (split across roles); higher commission, reduced base." },
  { name: "Ethan", email: "ethan@example.com", role: "rep", position: "acquisitions", irregularSchedule: true, note: "Part-time CA, no set schedule (exempt from missing-entry alerts). Listing appts for out-of-buy-box deals. Limited lead access." },
  { name: "Irish", email: "irish@example.com", role: "rep", position: "cc_lm", note: "Hybrid cold caller + lead manager (25h/wk). Stretch goal: 3 appts/day." },
  { name: "Sharyn", email: "sharyn@example.com", role: "rep", position: "dispositions", note: "" },
  { name: "Marie", email: "marie@example.com", role: "manager", position: "dispositions", note: "Manager access + own Dispositions scorecard." },
  { name: "Jon", email: "jon@example.com", role: "admin", position: "acquisitions", note: "Owner/admin + own Acquisitions scorecard." },
];

// Per-rep goal overrides (Target). period null = standing.
// Goals grounded in each person's proven non-zero daily averages from the sheet,
// set as a stretch (slightly above proven) and scaled to their hours.
const TARGETS = [
  // Michelle (37h, hybrid acquisitions + lead mgmt)
  { userName: "Michelle", kpiKey: "offers_made", goalValue: 2 },
  { userName: "Michelle", kpiKey: "acq_talk_time", goalValue: 90 * 60 }, // 1:30
  // Ethan (part-time, irregular) — gentle
  { userName: "Ethan", kpiKey: "offers_made", goalValue: 1 },
  // Sharyn (37h) — proven ~2x Marie
  { userName: "Sharyn", kpiKey: "buyers_contacted", goalValue: 140 },
  { userName: "Sharyn", kpiKey: "new_buyers", goalValue: 3 },
  { userName: "Sharyn", kpiKey: "deals_sold", goalValue: 4 },
  // Marie (25h) — base goals fit; explicit for clarity
  { userName: "Marie", kpiKey: "buyers_contacted", goalValue: 80 },
];

async function main() {
  await db.settings.upsert({ where: { id: 1 }, update: {}, create: { id: 1 } });

  for (const u of USERS) {
    await db.user.upsert({ where: { email: u.email }, update: u, create: u });
  }

  let order = 0;
  for (const k of KPIS) {
    order += 1;
    await db.kpi.upsert({
      where: { key: k.key },
      update: { ...k, sortOrder: order },
      create: { ...k, sortOrder: order },
    });
  }

  // Per-rep goal overrides.
  for (const t of TARGETS) {
    const kpi = await db.kpi.findUnique({ where: { key: t.kpiKey } });
    const user = await db.user.findFirst({ where: { name: t.userName } });
    if (!kpi || !user) continue;
    const existing = await db.target.findFirst({
      where: { kpiId: kpi.id, userId: user.id, period: null },
    });
    if (existing) {
      await db.target.update({ where: { id: existing.id }, data: { goalValue: t.goalValue } });
    } else {
      await db.target.create({
        data: { kpiId: kpi.id, userId: user.id, period: null, goalValue: t.goalValue },
      });
    }
  }

  console.log(
    `Seeded ${await db.user.count()} users, ${await db.kpi.count()} KPIs, ${await db.target.count()} targets.`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
