-- Closed-deal profit ledger from HUD statements (idempotent)
CREATE TABLE IF NOT EXISTS "ClosedDeal" (
  "id" TEXT NOT NULL,"address" TEXT NOT NULL,"city" TEXT NOT NULL DEFAULT '',"state" TEXT NOT NULL DEFAULT '',
  "closeDate" TEXT NOT NULL,"year" INTEGER NOT NULL,"month" INTEGER NOT NULL,"dealType" TEXT NOT NULL DEFAULT 'assignment',
  "profit" DOUBLE PRECISION NOT NULL,"notes" TEXT NOT NULL DEFAULT '',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ClosedDeal_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "ClosedDeal_address_closeDate_key" ON "ClosedDeal"("address","closeDate");
CREATE INDEX IF NOT EXISTS "ClosedDeal_year_idx" ON "ClosedDeal"("year");
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('63dd44eaca3c40688d04b184e9452747','2508 NE 12th St','Oklahoma City','OK','2023-10-27',2023,10,'assignment',14144,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('41ef8dd793b0461d9acd2d037521551a','4104 NW Liberty','Oklahoma City','OK','2024-02-02',2024,2,'assignment',18000,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('6274fa85237743a8972fbc12052b73f4','1315 NE 15th St','Oklahoma City','OK','2024-02-13',2024,2,'assignment',30500,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('4cb5f717a7fd43c6bc358943ae22f62b','1251 Leighton Ave','Los Angeles','CA','2024-09-19',2024,9,'assignment',90000,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('fdf192ca5ca242c68d62da29f8e4c1eb','701 NE 81st St','Oklahoma City','OK','2024-10-07',2024,10,'assignment',5000,'Memo filed; end buyer paid our $5k fee on a lost deal') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('8c5c36318d014a40b9f8f5116c85cd4d','3632 Country Club Blvd','Cape Coral','FL','2024-11-12',2024,11,'jv',5095.71,'JV - partner sold, sent our flat fee') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('93653e56c7f84634af5efcaaa7b9e948','1528 W Virginia St','San Bernardino','CA','2025-02-10',2025,2,'wholetail',136872,'Bought with Emet loan, wholetailed (cleaned + listed as-is). Net after escrow/loan/commissions + ~$200 cleanup. Highest ROI.') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('1d6624cc01574b5f8aa0713f7fc3a63b','8505 Fremontia Way','South Gate','CA','2025-04-02',2025,4,'assignment',27495.79,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('b9bc919e1ef54b7480cf68cb5589445a','Janice St (Vacant Land)','Inyokern','CA','2025-08-22',2025,8,'assignment',3889.2,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('bb3dcf676905499c9862f6edeada6a54','8845 Eve Ave','Inyokern','CA','2025-09-24',2025,9,'assignment',6351.79,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('dfe96b843e654c4a8e4e6c84a49ad880','3420 Scott St','Portsmouth','VA','2025-10-31',2025,10,'subject_to',1500,'Subject-to; smallest deal') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('d12599373b2f4fd19cda10fe96521e42','537 Murray St','Hutchins','TX','2026-03-17',2026,3,'assignment',10000,'') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
INSERT INTO "ClosedDeal" ("id","address","city","state","closeDate","year","month","dealType","profit","notes") VALUES ('74da813847734d8f8413c1a5326ba993','42075 Auberry Rd','Auberry','CA','2026-03-30',2026,3,'double_close',4606.3,'True double close; escrow paid twice') ON CONFLICT ("address","closeDate") DO UPDATE SET "profit"=EXCLUDED."profit","dealType"=EXCLUDED."dealType","notes"=EXCLUDED."notes";
