-- Populate team roster profiles (owner-only). Matched to User by first name.

INSERT INTO "TeamProfile" ("id","userId","name","birthday","phone","address","startDate","lastPromotion","payScale","payPeriod","payMethod","payDetails","about","performance","updatedAt")
SELECT 'tp_sharyn', u.id, 'Sharyn Kayle Mangubat', '2000-02-07', '+63 918 732 4354', 'Mindanao, Philippines', '2023-10-19', '2025-02-01', '$3.00/hr', 'hourly', 'Wise / PayPal', 'PayPal: sharynkaylemangubat@gmail.com - Wise: sharynmangubat02@gmail.com', 'Born Again. From Mindanao; lives with her partner and 10yo stepdaughter (preparing for marriage). VA since Feb 2022 - e-commerce, product sourcing, Amazon. Occasional power outages; also works a night shift for other clients. 2026 vision: grow in real estate (disposition, lead mgmt, client relations); prefers handling one task at a time. Resolutions: prioritize mental health; grow real estate knowledge. 2025: ~$400 dental help, personal loan during Amazon days, gifts, per-close bonuses, given Jon''s old MacBook.', 'Strong contributor. When Marie was chosen for VA Manager, assured Sharyn she was valued and placed where she''ll thrive.', now()
FROM "User" u WHERE u.name ILIKE 'Sharyn%' ORDER BY u."createdAt" LIMIT 1
ON CONFLICT ("userId") DO UPDATE SET "name"=EXCLUDED."name","birthday"=EXCLUDED."birthday","phone"=EXCLUDED."phone","address"=EXCLUDED."address","startDate"=EXCLUDED."startDate","lastPromotion"=EXCLUDED."lastPromotion","payScale"=EXCLUDED."payScale","payPeriod"=EXCLUDED."payPeriod","payMethod"=EXCLUDED."payMethod","payDetails"=EXCLUDED."payDetails","about"=EXCLUDED."about","performance"=EXCLUDED."performance", "updatedAt"=now();

INSERT INTO "TeamProfile" ("id","userId","name","birthday","phone","address","startDate","lastPromotion","payScale","payPeriod","payMethod","payDetails","about","performance","updatedAt")
SELECT 'tp_marie', u.id, 'Marie Badayos', '1994-08-17', '', 'Antipolo (east of Manila), Philippines', '2024-05-31', '2025-04-16', '$5.00/hr', 'hourly', 'Wise', 'Wise: rosemae08@gmail.com', 'Catholic. From Antipolo. Understands Bisaya but cannot speak it. Daughter Xyzcha (2yo in 2024, kindergarten in 2026). Probation completed Jul 1 2024; promoted to VA Manager Apr 16 2025. 2026 vision: a balanced, disciplined life and a confident, reliable leader - deepen performance-management, leadership, and run teams/KPIs/training independently. Resolutions: emotional balance; strong contributor to team & company. (Doc spelled surname ''Bajayos'' - confirm.)', 'Promoted to VA Manager (Apr 2025); more perks planned. Early needs were SMS/rapport and comping education.', now()
FROM "User" u WHERE u.name ILIKE 'Marie%' ORDER BY u."createdAt" LIMIT 1
ON CONFLICT ("userId") DO UPDATE SET "name"=EXCLUDED."name","birthday"=EXCLUDED."birthday","phone"=EXCLUDED."phone","address"=EXCLUDED."address","startDate"=EXCLUDED."startDate","lastPromotion"=EXCLUDED."lastPromotion","payScale"=EXCLUDED."payScale","payPeriod"=EXCLUDED."payPeriod","payMethod"=EXCLUDED."payMethod","payDetails"=EXCLUDED."payDetails","about"=EXCLUDED."about","performance"=EXCLUDED."performance", "updatedAt"=now();

INSERT INTO "TeamProfile" ("id","userId","name","birthday","phone","address","startDate","lastPromotion","payScale","payPeriod","payMethod","payDetails","about","performance","updatedAt")
SELECT 'tp_viktoriia', u.id, 'Viktoriia Arutiunova', '', '+420 608 600 901', 'Prague, Czech Republic', '2024-04-01', '', '9,500 CZK / month', 'monthly', 'Bank transfer (CZK)', '9,500 CZK on the 1st of each month', 'Based in Prague; Jon''s partner. Marketing + texting automation. Started ~Feb 19 2024, official on payroll Apr 1 2024. Birthday: November 3. 2026 resolutions: read 10 books and cut social media; learn new skills to grow income.', '', now()
FROM "User" u WHERE u.name ILIKE 'Viktoriia%' ORDER BY u."createdAt" LIMIT 1
ON CONFLICT ("userId") DO UPDATE SET "name"=EXCLUDED."name","birthday"=EXCLUDED."birthday","phone"=EXCLUDED."phone","address"=EXCLUDED."address","startDate"=EXCLUDED."startDate","lastPromotion"=EXCLUDED."lastPromotion","payScale"=EXCLUDED."payScale","payPeriod"=EXCLUDED."payPeriod","payMethod"=EXCLUDED."payMethod","payDetails"=EXCLUDED."payDetails","about"=EXCLUDED."about","performance"=EXCLUDED."performance", "updatedAt"=now();

INSERT INTO "TeamProfile" ("id","userId","name","birthday","phone","address","startDate","lastPromotion","payScale","payPeriod","payMethod","payDetails","about","performance","updatedAt")
SELECT 'tp_michelle', u.id, 'Michelle Ann Lagudas', '1996-11-21', '09075838165 (emergency)', 'Daanglungsod, Katipunan, Zamboanga del Norte, Philippines', '2025-08-11', '2025-08-16', '$3.00/hr', 'hourly', 'Wise', 'Wise: lagudasmitch@gmail.com', 'Catholic. From Mindanao; single. Started Aug 11 2025 as an Acquisition Trainee (LM track). 2026 resolutions: lose 8 kg (reach 60 kg); wake 30 min earlier to be more effective and contribute more ideas as an LM.', 'Acquisition trainee - early in the ramp.', now()
FROM "User" u WHERE u.name ILIKE 'Michelle%' ORDER BY u."createdAt" LIMIT 1
ON CONFLICT ("userId") DO UPDATE SET "name"=EXCLUDED."name","birthday"=EXCLUDED."birthday","phone"=EXCLUDED."phone","address"=EXCLUDED."address","startDate"=EXCLUDED."startDate","lastPromotion"=EXCLUDED."lastPromotion","payScale"=EXCLUDED."payScale","payPeriod"=EXCLUDED."payPeriod","payMethod"=EXCLUDED."payMethod","payDetails"=EXCLUDED."payDetails","about"=EXCLUDED."about","performance"=EXCLUDED."performance", "updatedAt"=now();

INSERT INTO "TeamProfile" ("id","userId","name","birthday","phone","address","startDate","lastPromotion","payScale","payPeriod","payMethod","payDetails","about","performance","updatedAt")
SELECT 'tp_ethan', u.id, 'Ethan De La Cruz', '', '', 'Central Valley, CA (between Bakersfield & Fresno), with parents', '2025-09-27', '', '15-20% bonus, no base pay', 'per-deal', 'US bank', 'US bank (Tucoemas FCU) - full account/routing kept in payroll, not stored here.', 'Hired Sep 27 2025. Former Realtor with an active license; on listings. Comp is a 15-20% bonus with no base. Employee ID (Chase): 09272025. 2026 resolutions: reach a healthy 225 lbs and learn Spanish; close 20 escrows.', 'Licensed agent; listings focus.', now()
FROM "User" u WHERE u.name ILIKE 'Ethan%' ORDER BY u."createdAt" LIMIT 1
ON CONFLICT ("userId") DO UPDATE SET "name"=EXCLUDED."name","birthday"=EXCLUDED."birthday","phone"=EXCLUDED."phone","address"=EXCLUDED."address","startDate"=EXCLUDED."startDate","lastPromotion"=EXCLUDED."lastPromotion","payScale"=EXCLUDED."payScale","payPeriod"=EXCLUDED."payPeriod","payMethod"=EXCLUDED."payMethod","payDetails"=EXCLUDED."payDetails","about"=EXCLUDED."about","performance"=EXCLUDED."performance", "updatedAt"=now();
